_target_: robot_io.cams.kinect4.kinect4.Kinect4
_recursive_: false
device: 0
align_depth_to_color: true
resolution: '720p'
undistort_image: true
resize_resolution: [300, 300]
crop_coords: [188, 644, 442, 898]
fps: 30
