_target_: vr_env.scene.play_table_scene.PlayTableScene
_recursive_: false
data_path: ${data_path}
global_scaling: 0.8
euler_obs: ${robot.euler_obs}
robot_base_position: [0.3, 0.15, 0.45]
robot_base_orientation: [0, 0, 1.5707963]
robot_initial_joint_positions: [-0.3457686708019129, -0.15454379621111053, -0.6607497652179231, -2.431721569843283, -0.12811896258574057, 2.3050911768605884, -0.128854091294185]
surfaces: []

objects:
  fixed_objects:
    table:
      file: table/hightable.urdf
      initial_pos: [0.3, 0.7, 0.02]
      initial_orn: [0, 0, 0]
      fixed: true
    bin:
      file: ais_objects/bin_10_30_50/bin_10_30_50.urdf
      initial_pos: [0.7, 0.75, 0.6]
      initial_orn: [1.57, 0, 0]
      fixed: true
  movable_objects:
    drill:
      file: 035_power_drill/google_16k/textured.urdf
      initial_pos: [0.13, 0.7, 0.62]
      initial_orn: [0, 0, 0]
      fixed: false
    marker:
      file: tabletop/marker/textured.urdf
      initial_pos: [0.43, 0.8, 0.618]
      initial_orn: [0, 0, 0]
      fixed: false
    spatula:
      file: tabletop/plaster_spatula/plaster_spatula.urdf
      initial_pos: [0.1, 0.45, 0.611]
      initial_orn: [0, 0, 0.5]
      fixed: false
    hammer:
      file: 048_hammer/google_16k/textured.urdf
      initial_pos: [-0.1, 0.85, 0.613]
      initial_orn: [0, 0, -0.3]
      fixed: false
    screwdriver:
      file: tabletop/flat_screwdriver/textured.urdf
      initial_pos: [-0.1, 0.45, 0.6214]
      initial_orn: [0, 0, -1.5]
      fixed: false
    utility_knife:
      file: tabletop/utility_knife/utility_knife.urdf
      initial_pos: [0.4, 0.5, 0.611]
      initial_orn: [0, 0, -1.54]
      fixed: false
    flashlight:
      file: tabletop/flashlight/flashlight.urdf
      initial_pos: [0.25, 0.9, 0.624]
      initial_orn: [0, 0, 0.1]
      fixed: false