_target_: robot_io.robot_interface.panda_frankx_interface.PandaFrankXInterface
_recursive_: false
fci_ip: "192.168.180.87"
urdf_path: "misc/panda_urdf/panda_longer_finger.urdf"
velocity_rel: 0.1
acceleration_rel: 0.1
jerk_rel: 0.1
#neutral_pose: [-1.6984557714179116, 0.9218021509267583, 1.8161416658658551, -2.418298423198231, -0.9560779526895947, 1.9015431017736373, 1.4820111242348053]
neutral_pose:  [-0.017792060227770554, -0.7601235411041661, 0.019782607023391807, -2.342050140544315, 0.029840531355804868, 1.5411935298621688, 0.7534486589746342]
workspace_limits:  [[0.4, -0.5, 0.041], [0.8, 0.5, 0.5]]  # [[x_min, y_min, z_min], [x_max, y_max, z_max]]
ll: [-2.8973, -1.7628, -2.8973, -3.0718, -2.8973, -0.0175, -2.8973]
ul: [2.8973, 1.7628, 2.8973, -0.0698, 2.8973, 3.7525, 2.8973]

contact_torque_threshold: 20
collision_torque_threshold: 100  # 20
contact_force_threshold: 10
collision_force_threshold: 100  # 30


use_impedance: true
#franka_joint_impedance: [300, 300, 300, 250, 250, 200, 200]
franka_joint_impedance:  [3000, 3000, 3000, 2500, 2500, 2000, 2000]
translational_stiffness: 500
rotational_stiffness: 25
damping_xi: [1, 1, 1, 0.3, 0.3, 0.3]
joint_stiffness: 200
use_nullspace: true
nullspace_stiffness: 10
q_d_nullspace: [-0.017792060227770554, -0.7601235411041661, 0.019782607023391807, -2.342050140544315, 0.029840531355804868, 1.5411935298621688, 0.7534486589746342]


gripper_speed: 1
gripper_force: 20
gripper_timeout: 2
gripper_opening_threshold: 0.04
gripper_closing_threshold: 0.04

relative_action_reference_frame: "desired"  # "current" or "desired"
relative_action_control_frame: "tcp"  # "tcp" or "world"
relative_pos_clip_threshold: 0.05
relative_rot_clip_threshold: 0.3
limit_control_5_dof: true

defaults:
  - ik: ik_fast_panda