save_dir: ../calibration/calibration_files
num_poses: 20
robot:
  use_impedance: false

hydra:
  run:
    dir: ${save_dir}

defaults:
  - env: env
  - robot: iiwa_interface
  - cams/gripper_cam@cam: realsense
  - marker_detector: apriltag_board
  - calibration/gripper_cam_pose_sampler@gripper_cam_pose_sampler: iiwa_sampler
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
