defaults:
  - paths: general_paths
  - model_cfg: default
  - transforms: grayscale
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
get_eval_files: True

# load model
model_path: ./hydra_outputs/affordance_model/2022-02-01/22-05-41
model_name: last.ckpt

dataset_name: tabletop/tabletop_kitchen
data_dir: ${paths.datasets}/${dataset_name}

# For visualization
out_size: 200
save_images: False
imshow: True
output_dir: ./predictions/

# Uncomment to specify a camera, otherwise it will look for the folder of the camera used for training
# cam_data: static

#-- Hydra config --#
# hydra output will be stored to save_dir
save_dir: ./hydra_outputs/viz/
hydra:
  run:
    dir: ${save_dir}/viz # Output directory for normal runs
